WIP: MI-260: Create API endpoint for login with LTI and validate LTI Launch fields
Brightscout/mattermost-server pull request #1
Opened 2019-01-14 08:50 UTC by chetanyakan

#### Summary
- Create an API endpoint to Login with LTI which takes a POST request with LTI launch fields.
- Iterate over LTI config to find consumer secret using consumer key in the request
- Validate consumer key by validating OAuth Signature of the LTI launch fields.

#### Ticket Link
https://brightscout.atlassian.net/browse/MI-257
https://brightscout.atlassian.net/browse/MI-260
https://brightscout.atlassian.net/browse/MI-261

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

2019-01-14 11:56 UTC, harshilsharma63 requested changes

2019-01-14 11:56 UTC, harshilsharma63 commented on app/lti.go
> +// Copyright (c) 2017-present Mattermost, Inc. All Rights Reserved.
I don't think this code belongs to the app layer of Mattermost. It's more of a utility.

2019-01-14 11:56 UTC, harshilsharma commented on model/config.go
> +type LMSOAuthSettings struct {
Refactor the types as discussed.

2019-01-14 11:56 UTC, harshilsharma commented on web/lti.go
> +
Please remove the empty line.

2019-01-14 16:21 UTC, chetanyakan commented on web/lti.go
> +
Done

2019-01-15 12:17 UTC, chetanyakan commented on model/config.go
> +type LMSOAuthSettings struct {
Done

2019-01-15 13:00 UTC, harshilsharma63 requested changes

2019-01-15 13:00 UTC, harshilsharma63 commented on config/config-dev.json
> +    "LtiSettings": {
This should be `LTISettings` (capital LTI).

2019-01-15 13:00 UTC, harshilsharma63 commented on model/config.go
> +type EdxLMSSettings struct {
Formatting seems to be a bit off over here. Can you run `gofmt` on the file?

2019-01-15 13:00 UTC, harshilsharma63 commented on model/config.go
> +type LMSOAuthSettings struct {
Let's move all this logic to `model/lti.go` to avoid conflicts with Mattermost.

2019-01-15 13:00 UTC, harshilsharma63 commented on model/config.go
> +	Name  string
This should extend `LMSSettings`.

2019-01-15 13:00 UTC, harshilsharma63 commented on web/lti.go
> +		if lms, ok := val.(model.EdxLMSSettings); ok {
We should cast this to `LMSSettings` and not any of the sub-types.

2019-01-15 13:00 UTC, harshilsharma63 commented on web/lti.go
> +
Can we check over here whether we found a consumer secret or not? If not found we can add a log statement about that.

2019-01-15 13:06 UTC, chetanyakan commented on web/lti.go
> +
Done

2019-01-15 13:08 UTC, chetanyakan commented on model/config.go
> +type EdxLMSSettings struct {
Done

2019-01-15 13:08 UTC, chetanyakan commented on model/config.go
> +type LMSOAuthSettings struct {
Done

2019-01-15 13:08 UTC, chetanyakan commented on model/config.go
> +	Name  string
Done

2019-01-15 13:09 UTC, chetanyakan commented on web/lti.go
> +		if lms, ok := val.(model.EdxLMSSettings); ok {
As discussed, added a todo to handle that later

2019-01-15 13:09 UTC, chetanyakan commented on web/lti.go
> +
Done

2019-01-15 13:09 UTC, chetanyakan commented on config/config-dev.json
> +    "LtiSettings": {
Done

2019-01-16 08:55 UTC, harshilsharma63 approved these changes

2019-01-16 08:58 UTC, merged