Mi-1278: Add Comments and lint fix
Brightscout/mattermost-server pull request #27
Opened 2021-05-26 08:18 UTC by hrishavkmr

2021-05-26 08:36 UTC, chetanyakan requested changes

2021-05-26 08:36 UTC, chetanyakan commented on app/lti.go
> +//
Explain what happens when
- LTI plugin is not installed
- LTI plugin is enabled/disabled

2021-05-26 08:36 UTC, chetanyakan commented on app/lti.go
> +		return nil, fmt.Errorf("Error unmarshaling LTI Config from json: %s", err.Error())
use `errors.Wrap` instead

2021-05-26 08:36 UTC, chetanyakan commented on config/client.go
> +		//
You don't have to add comments about things that can be easily understood from readable code.

Instead, explain why these changes are needed.

E.g. here, you could mention what this code block does, i.e. add a client config parameter to allow the webapp to check if signup with LTI is enabled.

2021-05-26 08:36 UTC, chetanyakan commented on model/lti.go
> +	// plugin id of lti configuration plugin
1. Comment over constant should start with constant name. 
2. mention what this plugin is used for.
e.g. LTI_PLUGIN_ID is the ID of the plugin used to maintain the LTI settings.

2021-05-26 08:36 UTC, chetanyakan commented on web/lti.go
> +	//
this comment is not helpful. it's better if you remove this and similar comments.

2021-05-26 10:40 UTC, manojmalik20 approved these changes

2021-05-27 07:11 UTC, chetanyakan commented on app/lti.go
> +//
what about this?

2021-05-27 09:22 UTC, chetanyakan approved these changes

2021-05-27 09:27 UTC, merged