MI-285 Restructured LTI config structure
Brightscout/mattermost-server pull request #7
Opened 2019-01-23 10:02 UTC by harshilsharma

#### Summary
Restructured LTI config structure to make querying easier and to accommodate more items such as default channel list.

2019-01-23 10:22 UTC, chetanyakan commented on i18n/en.json
> +    "translation": "There was an error with LTI signup attempt. Please try again or contact your system administrator. Error code LTI-9"
Remove this

2019-01-24 10:33 UTC, chetanyakan requested changes

2019-01-24 10:33 UTC, chetanyakan commented on config/config-dev.json
> -                "Name": "Appsembler",
Check if we would need a name field as well.

2019-01-24 10:33 UTC, chetanyakan commented on model/edx.go
> +	Name				string
Run `gofmt`.

2019-01-24 11:29 UTC, harshilsharma63 commented on model/edx.go
> +	Name				string
Done.

2019-01-24 11:29 UTC, merged